name: Build Geode Mod

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: geode-sdk/build-geode-mod@main
        with:
          # Optional: Specify SDK version (e.g., 'latest' or 'nightly')
          sdk: latest
